name: Build and Test React App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository #se clona en el entorno de github para ejecutarse
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16

    - name: Install dependencies
      run: npm install

    - name: Build and Test
      run: npm run build && npm test
